/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Account;
import Controller.AccountCB;
import Controller.AccountSV;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Model.AccountModel;
import Model.AccountModelCB;
import Model.AccountModelSV;

/**
 *
 * @author .K
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_taiKhoan = new javax.swing.JTextField();
        txt_matKhau = new javax.swing.JPasswordField();
        btn_dangNhap = new javax.swing.JButton();
        lb_thongbao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_dangNhap1 = new javax.swing.JButton();
        btn_dangNhap2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setLabelFor(txt_taiKhoan);
        jLabel2.setText("Tài Khoản");

        jLabel3.setText("Mật Khẩu");

        txt_matKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matKhauActionPerformed(evt);
            }
        });

        btn_dangNhap.setText("Đăng Nhập (admin)");
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-dai-hoc-cong-nghiep-ha-noi-inkythuatso-01-21-15-51-20.jpg"))); // NOI18N

        btn_dangNhap1.setText("Đăng Nhập (sinh viên)");
        btn_dangNhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhap1ActionPerformed(evt);
            }
        });

        btn_dangNhap2.setText("Đăng Nhập (cán bộ coi thi)");
        btn_dangNhap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhap2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_taiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_matKhau))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(lb_thongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_dangNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_dangNhap)
                        .addGap(12, 12, 12)
                        .addComponent(btn_dangNhap2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_taiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lb_thongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dangNhap)
                    .addComponent(btn_dangNhap1)
                    .addComponent(btn_dangNhap2))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_matKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matKhauActionPerformed

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        ArrayList<AccountModel> danhsach = new ArrayList<>();
        String tk = txt_taiKhoan.getText();
        String mk = txt_matKhau.getText();
        try {
            danhsach = Account.danh_sach_TK();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if (txt_taiKhoan.getText().equals("") || txt_taiKhoan.getText().equals("Nhập tài khoản...")) {
                lb_thongbao.setText("Vui lòng nhập tài khoản");
                txt_taiKhoan.requestFocus();
            } else if (String.valueOf(txt_matKhau.getPassword()).equals("")) {
                lb_thongbao.setText("Vui lòng nhập mật khẩu");
                txt_matKhau.requestFocus();
            } else {
                AccountModel A = new AccountModel(txt_taiKhoan.getText());
                if(danhsach.contains(A)){
                    if(tk.equals(danhsach.get(danhsach.indexOf(A)).getUsername()) && mk.equals(danhsach.get(danhsach.indexOf(A)).getPassword())){
                        Home f = new Home();
                        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                        f.setLocationRelativeTo(null);
                        f.setResizable(false);
                        f.setVisible(true);
                        this.dispose();
                    }else {
                        lb_thongbao.setText("Sai mật khẩu");
                    }
                 
                }else{
                    lb_thongbao.setText("Sai thông tin đăng nhập");
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    private void btn_dangNhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhap1ActionPerformed
        ArrayList<AccountModelSV> danhsach = new ArrayList<>();
        String tk = txt_taiKhoan.getText();
        String mk = txt_matKhau.getText();
        try {
            danhsach = AccountSV.danh_sach_TK();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if (txt_taiKhoan.getText().equals("") || txt_taiKhoan.getText().equals("Nhập tài khoản...")) {
                lb_thongbao.setText("Vui lòng nhập tài khoản");
                txt_taiKhoan.requestFocus();
            } else if (String.valueOf(txt_matKhau.getPassword()).equals("")) {
                lb_thongbao.setText("Vui lòng nhập mật khẩu");
                txt_matKhau.requestFocus();
            } else {
                AccountModelSV A = new AccountModelSV(txt_taiKhoan.getText());
                if(danhsach.contains(A)){
                    if(tk.equals(danhsach.get(danhsach.indexOf(A)).getUsername()) && mk.equals(danhsach.get(danhsach.indexOf(A)).getPassword())){
                        SinhVienXemLichThi f = new SinhVienXemLichThi();
                        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                        f.setLocationRelativeTo(null);
                        f.setResizable(false);
                        f.setVisible(true);
                        this.dispose();
                    }else {
                        lb_thongbao.setText("Sai mật khẩu");
                    }
                 
                }else{
                    lb_thongbao.setText("Sai thông tin đăng nhập");
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_dangNhap1ActionPerformed

    private void btn_dangNhap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhap2ActionPerformed
       ArrayList<AccountModelCB> danhsach = new ArrayList<>();
        String tk = txt_taiKhoan.getText();
        String mk = txt_matKhau.getText();
        try {
            danhsach = AccountCB.danh_sach_TK();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if (txt_taiKhoan.getText().equals("") || txt_taiKhoan.getText().equals("Nhập tài khoản...")) {
                lb_thongbao.setText("Vui lòng nhập tài khoản");
                txt_taiKhoan.requestFocus();
            } else if (String.valueOf(txt_matKhau.getPassword()).equals("")) {
                lb_thongbao.setText("Vui lòng nhập mật khẩu");
                txt_matKhau.requestFocus();
            } else {
                AccountModelCB A = new AccountModelCB(txt_taiKhoan.getText());
                if(danhsach.contains(A)){
                    if(tk.equals(danhsach.get(danhsach.indexOf(A)).getUsername()) && mk.equals(danhsach.get(danhsach.indexOf(A)).getPassword())){
                        CanBoXemLichThi f = new CanBoXemLichThi();
                        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                        f.setLocationRelativeTo(null);
                        f.setResizable(false);
                        f.setVisible(true);
                        this.dispose();
                    }else {
                        lb_thongbao.setText("Sai mật khẩu");
                    }
                 
                }else{
                    lb_thongbao.setText("Sai thông tin đăng nhập");
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_dangNhap2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JButton btn_dangNhap1;
    private javax.swing.JButton btn_dangNhap2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_thongbao;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JTextField txt_taiKhoan;
    // End of variables declaration//GEN-END:variables
}
