/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Dot;
import Model.Khoa;
import Model.Ky;
import Table.TableMonThi;
import Model.MonThi;
import Model.PhongThi;
import Utils.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author admin
 */
public class QuanLyMonThi extends javax.swing.JFrame {
    ArrayList<MonThi> dsMonThi = new ArrayList<MonThi>();
    ArrayList<Khoa> dsKhoa=new ArrayList<Khoa>();
    ArrayList<Ky> dsKy=new ArrayList<Ky>();
    ArrayList<Dot> dsDot=new ArrayList<Dot>();
    ArrayList<PhongThi> dsPhongThi=new ArrayList<PhongThi>();
    
    
    int dongchon = -1;
    
    MonThi monthi = new MonThi();
    Khoa khoa=new Khoa();
    Ky ky=new Ky();
    Dot dot=new Dot();
    PhongThi phong=new PhongThi();
    /**
     * Creates new form QuanLyMonThi
     */
    public QuanLyMonThi() {
        initComponents();
        LoadTableFromFile();
        LoadTableMonThi();
        indexComboBox();
        
    }
    
    void LoadTableFromFile(){
        File f = new File("danhSachMonThi.txt");
        File f1 = new File("danhSachKhoa.txt");
        File f2 = new File("danhSachKy.txt");
        File f3 = new File("danhSachDot.txt");
        File f4=new File("danhSachPhongThi.txt");
        ArrayList<String> list = f.ReadFromFile();
        ArrayList<String> listkhoa = f1.ReadFromFile();
        ArrayList<String> listky = f2.ReadFromFile();
        ArrayList<String> listdot = f3.ReadFromFile();
        ArrayList<String> listphong = f4.ReadFromFile();
        for(String s : list){
            String[] txt = s.split(",");
            monthi = new MonThi(txt[0],txt[1],txt[2],txt[3],txt[4],txt[5],txt[6]);
            dsMonThi.add(monthi);
        }
        for(String s : listkhoa){
            String[] txt = s.split(",");
            khoa = new Khoa(txt[0],txt[1]);
            dsKhoa.add(khoa);
        }
        for(String s : listky){
            String[] txt = s.split(",");
            ky = new Ky(txt[0],txt[1]);
            dsKy.add(ky);
        }
        for(String s : listdot){
            String[] txt = s.split(",");
            dot = new Dot(txt[0],txt[1]);
            dsDot.add(dot);
        }
        for(String s : listphong){
            String[] txt = s.split(",");
            phong = new PhongThi(txt[0],txt[1]);
            dsPhongThi.add(phong);
        }
    }
    
    public void LoadTableMonThi(){
        
       jTableMonThi.setModel(new TableMonThi(dsMonThi));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaMon = new javax.swing.JTextField();
        txtTenMon = new javax.swing.JTextField();
        txtThoiGianThi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMonThi = new javax.swing.JTable();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonSapXep = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbKhoa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbKy = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbDot = new javax.swing.JComboBox<>();
        cbPhongThi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ MÔN THI");

        jLabel2.setText("Mã môn:");

        jLabel3.setText("Tên môn:");

        jLabel4.setText("Thời gian thi:");

        jLabel5.setText("Phòng thi:");

        jTableMonThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã môn", "Tên môn", "Ngày thi", "Phòng thi", "Khoa", "Kỳ", "Đợt"
            }
        ));
        jTableMonThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMonThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMonThi);

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonSapXep.setText("Sắp xếp");
        jButtonSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSapXepActionPerformed(evt);
            }
        });

        jLabel6.setText("Khoa:");

        cbKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Kỳ:");

        cbKy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Đợt: ");

        cbDot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDotActionPerformed(evt);
            }
        });

        cbPhongThi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTenMon, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(txtMaMon))
                                .addGap(85, 85, 85))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtThoiGianThi, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(cbPhongThi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonThem)
                            .addGap(59, 59, 59)
                            .addComponent(jButtonSua)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSapXep)
                            .addGap(63, 63, 63)
                            .addComponent(jButtonXoa))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThoiGianThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPhongThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem)
                    .addComponent(jButtonSua)
                    .addComponent(jButtonXoa)
                    .addComponent(jButtonSapXep))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean ktraTrungMa(String a)
    {
        boolean ok = true;
        for(MonThi i:dsMonThi)
        {
            if(i.getMaMon().equalsIgnoreCase(a))
                ok = false;
        }
        return ok;
    }
    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        
        try{
            if(txtMaMon.getText().equals("")|| txtTenMon.getText().equals("") || txtThoiGianThi.getText().equals(""))
            {
                JOptionPane.showMessageDialog(rootPane," Bạn cần điền đầy đủ dữ kiện");
            }
            else{
                if(ktraTrungMa(txtMaMon.getText()))
                {
                    String phongthi = cbPhongThi.getSelectedItem().toString();
                    String khoa = cbKhoa.getSelectedItem().toString();
                    String ky = cbKy.getSelectedItem().toString();
                    String dot = cbDot.getSelectedItem().toString();
                    monthi = new MonThi(txtMaMon.getText(), txtTenMon.getText(),txtThoiGianThi.getText() ,phongthi,khoa,ky,dot);
                    dsMonThi.add(monthi);
                    //File f = new File("danhSachMonThi.txt");
                    //f.WriteToFile(monthi.toString());
                    LoadTableMonThi();
                   }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Mã môn này đã tồn tại!");
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void WriteTableToFile(){
        try {
                FileWriter fr = new FileWriter("danhSachMonThi.txt");
                for(MonThi mon : dsMonThi){
                    fr.write(mon.toString() + "\n");
                }
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(QuanLyMonThi.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        dongchon = jTableMonThi.getSelectedRow();
        if(dongchon !=-1){
            String phongthi = cbPhongThi.getSelectedItem().toString();
            String khoa = cbKhoa.getSelectedItem().toString();
        String ky = cbKy.getSelectedItem().toString();
        String dot = cbDot.getSelectedItem().toString();
        MonThi monthiNew = new MonThi(txtMaMon.getText(), txtTenMon.getText(),txtThoiGianThi.getText() ,phongthi,khoa,ky,dot);
            dsMonThi.set(dongchon,monthiNew);
            WriteTableToFile();
            LoadTableMonThi();
        }else{
            JOptionPane.showConfirmDialog(this,"Bạn chưa chọn dòng để sửa!","Thông báo", WIDTH);
        }
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        dongchon = jTableMonThi.getSelectedRow();
        if(dongchon !=-1){
            dsMonThi.remove(dongchon);
            WriteTableToFile();
            LoadTableMonThi();
        }else{
            JOptionPane.showConfirmDialog(this,"Bạn chưa chọn dòng để xóa!","Thông báo", WIDTH);
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jTableMonThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMonThiMouseClicked
        // TODO add your handling code here:
        dongchon = jTableMonThi.getSelectedRow();
        if(dongchon !=-1){
            monthi = dsMonThi.get(dongchon);
            txtMaMon.setText(monthi.getMaMon()+"");
            txtTenMon.setText(monthi.getTenMon()+"");
            txtThoiGianThi.setText(monthi.getThoiGianThi()+"");
            cbPhongThi.setSelectedItem(monthi.getPhongThi()+"");
            cbKhoa.setSelectedItem(monthi.getKhoa()+"");
            cbKy.setSelectedItem(monthi.getKy()+"");
            cbDot.setSelectedItem(monthi.getDot()+"");
        }
    }//GEN-LAST:event_jTableMonThiMouseClicked

    private void jButtonSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSapXepActionPerformed
        // TODO add your handling code here:
        Comparator<MonThi> c = new Comparator<MonThi>() {
            @Override
            public int compare(MonThi t, MonThi t1) {
                return t.getTenMon().compareToIgnoreCase(t1.getTenMon());
            }
        };
        
        Collections.sort(dsMonThi,c);
        WriteTableToFile();
        LoadTableMonThi();
    }//GEN-LAST:event_jButtonSapXepActionPerformed

    private void cbDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ret=JOptionPane.showConfirmDialog(null,
                "bạn chắc chắn muốn thoát?", "Thoát",
                JOptionPane.YES_NO_OPTION);
        if(ret==JOptionPane.YES_OPTION){
            new Home().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    void indexComboBox(){
        cbPhongThi.removeAllItems();
        for(PhongThi i :dsPhongThi){
            cbPhongThi.addItem(i.getTenPhong());
        }
        cbKhoa.removeAllItems();
        for(Khoa i :dsKhoa){
            cbKhoa.addItem(i.getTenKhoa());
        }
        cbKy.removeAllItems();
        for(Ky i :dsKy){
            cbKy.addItem(i.getTenKy());
        }
        cbDot.removeAllItems();
        for(Dot i :dsDot){
            cbDot.addItem(i.getTenDot());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMonThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMonThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDot;
    private javax.swing.JComboBox<String> cbKhoa;
    private javax.swing.JComboBox<String> cbKy;
    private javax.swing.JComboBox<String> cbPhongThi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSapXep;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMonThi;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtTenMon;
    private javax.swing.JTextField txtThoiGianThi;
    // End of variables declaration//GEN-END:variables

    
}
