/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Table.TablePhongThi;
import Model.PhongThi;
import Utils.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author admin
 */
public class QuanLyPhongThi extends javax.swing.JFrame {
    
    ArrayList<PhongThi> dsPhongThi = new ArrayList<PhongThi>();
    
    int dongchon = -1;
    
    PhongThi phongthi = new PhongThi();
    /**
     * Creates new form QuanLyPhongThi
     */
    public QuanLyPhongThi() {
        initComponents();
        LoadTableFromFile();
        LoadTablePhongThi();
    }
    
    void LoadTableFromFile(){
        File f = new File("danhSachPhongThi.txt");
        ArrayList<String> list = f.ReadFromFile();
        for(String s : list){
            String[] txt = s.split(",");
            phongthi = new PhongThi(txt[0],txt[1]);
            dsPhongThi.add(phongthi);
        }
    }
    
    private void WriteTableToFile(){
        try {
                FileWriter fr = new FileWriter("danhSachPhongThi.txt");
                for(PhongThi p : dsPhongThi){
                    fr.write(p.getMaPhong() + "," + p.getTenPhong() + "\n");
                }
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(QuanLyMonThi.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    boolean ktraTrungMaPhong(String a)
    {
        boolean ok = true;
        for(PhongThi i:dsPhongThi)
        {
            if(i.getMaPhong().equalsIgnoreCase(a))
                ok = false;
        }
        return ok;
    }
    
    public void LoadTablePhongThi(){
       jTableQuanLyPhongThi.setModel(new TablePhongThi(dsPhongThi));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMaPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTenPhong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuanLyPhongThi = new javax.swing.JTable();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ PHÒNG THI");

        jLabel2.setText("Mã phòng:");

        jLabel3.setText("Tên phòng:");

        jTableQuanLyPhongThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã phòng", "Tên phòng"
            }
        ));
        jTableQuanLyPhongThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQuanLyPhongThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableQuanLyPhongThi);

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonThem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldTenPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(jTextFieldMaPhong))
                    .addComponent(jButtonSua)
                    .addComponent(jButtonXoa))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonThoat)
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThoat)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(jButtonThem)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonSua)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonXoa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
      
       
        try{
            if(jTextFieldMaPhong.getText().equals("")|| jTextFieldTenPhong.getText().equals("") )
            {
                JOptionPane.showMessageDialog(rootPane," Bạn cần điền đầy đủ dữ kiện");
            }
            else{
                if(ktraTrungMaPhong(jTextFieldMaPhong.getText()))
                {
               
                    phongthi = new PhongThi(jTextFieldMaPhong.getText().toString(), jTextFieldTenPhong.getText().toString());
                    File f = new File("danhSachPhongThi.txt");
                    f.WriteToFile(phongthi.toString());
                    dsPhongThi.add(phongthi);
                    LoadTablePhongThi();
                   }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Mã phòng này đã tồn tại");
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        dongchon = jTableQuanLyPhongThi.getSelectedRow();
        if(dongchon !=-1){
            
            PhongThi phongthiNew = new PhongThi(jTextFieldMaPhong.getText(), jTextFieldTenPhong.getText());
            dsPhongThi.set(dongchon,phongthiNew);
            WriteTableToFile();
            LoadTablePhongThi();
        }else{
            JOptionPane.showConfirmDialog(this,"Bạn chưa chọn dòng để sửa!","Thông báo", WIDTH);
        }
        
        try{
            if(jTextFieldMaPhong.getText().equals("")|| jTextFieldTenPhong.getText().equals("") )
            {
                JOptionPane.showMessageDialog(rootPane," Bạn cần điền đầy đủ dữ kiện");
            }
            else{
                if(ktraTrungMaPhong(jTextFieldMaPhong.getText()))
                {
               
                    phongthi = new PhongThi(jTextFieldMaPhong.getText().toString(), jTextFieldTenPhong.getText().toString());
                    File f = new File("danhSachPhongThi.txt");
                    f.WriteToFile(phongthi.toString());
                    dsPhongThi.add(phongthi);
                    LoadTablePhongThi();
                   }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        dongchon = jTableQuanLyPhongThi.getSelectedRow();
        if(dongchon !=-1){
            dsPhongThi.remove(dongchon);
            WriteTableToFile();
            LoadTablePhongThi();
        }else{
            JOptionPane.showConfirmDialog(this,"Bạn chưa chọn dòng để xóa!","Thông báo", WIDTH);
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jTableQuanLyPhongThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuanLyPhongThiMouseClicked
        // TODO add your handling code here:
        dongchon = jTableQuanLyPhongThi.getSelectedRow();
        if(dongchon !=-1){
            phongthi = dsPhongThi.get(dongchon);
            jTextFieldMaPhong.setText(phongthi.getMaPhong()+"");
            jTextFieldTenPhong.setText(phongthi.getTenPhong()+"");
    
        }
    }//GEN-LAST:event_jTableQuanLyPhongThiMouseClicked

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        int ret=JOptionPane.showConfirmDialog(null,
                "bạn chắc chắn muốn thoát?", "Thoát",
                JOptionPane.YES_NO_OPTION);
        if(ret==JOptionPane.YES_OPTION){
            new Home().setVisible(true);
            this.setVisible(false);
        }    
    }//GEN-LAST:event_jButtonThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhongThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableQuanLyPhongThi;
    private javax.swing.JTextField jTextFieldMaPhong;
    private javax.swing.JTextField jTextFieldTenPhong;
    // End of variables declaration//GEN-END:variables
}
